name: ADD_TO_PROJECT

on:
  issues:
    types:
      - opened
      - transferred
      - labeled
  pull_request:
    types:
      - opened
      - labeled

jobs:
  Exec:
    name: Add issue to project
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@d79571d8737ce0caa0120f44b15f2bc8f193d11a
        with:
          project-url: ${{ secrets.CONNECTORS_PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: connectors
