name: NIGHTLY
on:
  schedule:
    - cron: '0 18 * * *'
jobs:
  Build_nightly:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          files:
          - 'dist/camunda-modeler-nightly-linux-x64.tar.gz'
        - os: macos-12
          files:
          - 'dist/camunda-modeler-nightly-mac-arm64.dmg'
          - 'dist/camunda-modeler-nightly-mac-arm64.zip'
          - 'dist/camunda-modeler-nightly-mac-x64.dmg'
          - 'dist/camunda-modeler-nightly-mac-x64.zip'
        - os: windows-2022
          files:
          - 'dist/camunda-modeler-nightly-win-ia32.zip'
          - 'dist/camunda-modeler-nightly-win-x64.zip'
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependencies
      run: npm ci

    - name: Build nightly (Linux)
      if: ${{ runner.os == 'Linux' }}
      env:
        CSC_LINK: "${{ secrets.CSC_LINK }}"
        CSC_KEY_PASSWORD: "${{ secrets.CSC_KEY_PASSWORD }}"
        MIXPANEL_TOKEN: "${{ secrets.MIXPANEL_PROJECT_TOKEN }}"
        MIXPANEL_STAGE: "int"
        NIGHTLY: 1
        SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}"
        SENTRY_DSN: "${{ secrets.SENTRY_DSN }}"
        SENTRY_ORG: "${{ secrets.SENTRY_ORG }}"
        SENTRY_PROJECT: "${{ secrets.SENTRY_PROJECT }}"
        UPDATES_SERVER_PRODUCT_NAME: "${{ secrets.UPDATES_SERVER_PRODUCT_NAME }}"
      run: npm run build -- --linux

    - name: Build nightly (MacOS)
      if: ${{ runner.os == 'macOS' }}
      env:
        APPLE_DEVELOPER_ID: "${{ secrets.APPLE_DEVELOPER_ID }}"
        APPLE_DEVELOPER_ID_PASSWORD: "${{ secrets.APPLE_DEVELOPER_ID_PASSWORD }}"
        APPLE_TEAM_ID: "${{ secrets.APPLE_TEAM_ID }}"
        CSC_LINK: "${{ secrets.CSC_LINK }}"
        CSC_KEY_PASSWORD: "${{ secrets.CSC_KEY_PASSWORD }}"
        MIXPANEL_TOKEN: "${{ secrets.MIXPANEL_PROJECT_TOKEN }}"
        MIXPANEL_STAGE: "int"
        NIGHTLY: 1
        SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}"
        SENTRY_DSN: "${{ secrets.SENTRY_DSN }}"
        SENTRY_ORG: "${{ secrets.SENTRY_ORG }}"
        SENTRY_PROJECT: "${{ secrets.SENTRY_PROJECT }}"
        UPDATES_SERVER_PRODUCT_NAME: "${{ secrets.UPDATES_SERVER_PRODUCT_NAME }}"
      run: npm run build -- --mac

    - name: Build nightly (Windows)
      if: ${{ runner.os == 'Windows' }}
      env:
        MIXPANEL_TOKEN: "${{ secrets.MIXPANEL_PROJECT_TOKEN }}"
        MIXPANEL_STAGE: "int"
        NIGHTLY: 1
        SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}"
        SENTRY_DSN: "${{ secrets.SENTRY_DSN }}"
        SENTRY_ORG: "${{ secrets.SENTRY_ORG }}"
        SENTRY_PROJECT: "${{ secrets.SENTRY_PROJECT }}"
        UPDATES_SERVER_PRODUCT_NAME: "${{ secrets.UPDATES_SERVER_PRODUCT_NAME }}"
      run: npm run build -- --win

    - name: Import Secrets
      id: secrets
      uses: hashicorp/vault-action@v3.0.0
      with:
        url: ${{ secrets.VAULT_ADDR }}
        method: approle
        roleId: ${{ secrets.VAULT_ROLE_ID }}
        secretId: ${{ secrets.VAULT_SECRET_ID }}
        exportEnv: false
        secrets: |
          secret/data/common/jenkins/downloads-camunda-cloud_google_sa_key DOWNLOAD_CENTER_GCLOUD_KEY_BYTES | GCP_CREDENTIALS_NAME;
    - name: Upload artifact to Camunda Download Center
      uses: camunda/infra-global-github-actions/download-center-upload@ec5fc576ebd7dc1403d9be1dbfdfc53be6370958
      with:
        gcp_credentials: ${{ steps.secrets.outputs.GCP_CREDENTIALS_NAME }}
        env: 'prod'
        artifact_subpath: 'nightly'
        artifact_file: "${{ join(matrix.files, ' ') }}"

  Post-Failure:
    needs: Build_nightly
    if: failure()
    runs-on: ubuntu-latest
    steps:
    - name: Post to a Slack channel
      uses: slackapi/slack-github-action@v1.15.0
      with:
        channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
        slack-message: "Nightly build failed. <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Go to the build.>"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
